<?php

include_once 'Highway.php';

final class MotorWay extends Highway
{

    public function __construct()
    {
        $this->maxSpeed =130;
        $this->nbLane =4;
    }

    protected function setMaxSpeed($maxSpeed)
    {
        parent::setMaxSpeed($maxSpeed); // TODO: Change the autogenerated stub
        $this->setMaxSpeed(130);
    }

    protected function setNbLane($nbLane)
    {
        parent::setNbLane($nbLane); // TODO: Change the autogenerated stub
        $this->setNbLane(4);
    }

    public function addVehicule($vehicule)
    {
        if($vehicule instanceof Car) {
            $this->currentVehicle[]=$vehicule;
        }

    }

}