<?php


final class PedestrianWay extends Highway
{
    public function __construct()
    {
        $this->maxSpeed =10;
        $this->nbLane =1;
    }


    protected function setMaxSpeed($maxSpeed)
    {
        parent::setMaxSpeed($maxSpeed); // TODO: Change the autogenerated stub
        $this->setMaxSpeed(10);
    }

    protected function setNbLane($nbLane)
    {
        parent::setNbLane($nbLane); // TODO: Change the autogenerated stub
        $this->setNbLane(1);
    }

    public function addVehicule($vehicule)
    {
        if($vehicule instanceof Vehicle) {
            $this->currentVehicle[]=$vehicule;
        }

    }
}