<?php


class ResidentialWay extends Highway
{

    public function __construct()
    {
        $this->maxSpeed =50;
        $this->nbLane =2;
    }
    protected function setMaxSpeed($maxSpeed)
    {
        parent::setMaxSpeed($maxSpeed); // TODO: Change the autogenerated stub
        $this->setMaxSpeed(50);
    }

    protected function setNbLane($nbLane)
    {
        parent::setNbLane($nbLane); // TODO: Change the autogenerated stub
        $this->setNbLane(2);
    }

    public function addVehicule($vehicule)
    {
        if($vehicule instanceof Bike OR $vehicule instanceof Skateboard) {
            $this->currentVehicle[]=$vehicule;
        }

    }
}